kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mike-rolebinding
subjects:
- kind: User
  name: mike@foo-corp.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: foo-admin
  apiGroup: rbac.authorization.k8s.io
