---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    configmanagement.gke.io/cluster-name: defaultcluster
    configmanagement.gke.io/namespace-selector: gamestore-selector
    configmanagement.gke.io/source-path: config/namespaces/eng/quota.yaml
    configsync.gke.io/declared-fields: '{"f:metadata":{"f:annotations":{"f:configmanagement.gke.io/namespace-selector":{}}},"f:spec":{"f:hard":{"f:pods":{},"f:secrets":{}}}}'
  labels:
    configsync.gke.io/declared-version: v1
  name: pod-quota
  namespace: gamestore
spec:
  hard:
    pods: "5"
    secrets: "10"
